### ISSUE TITLE
Unnecessary checks in the  test_OutputCreated() function

### ISSUE THREAD

**Issue by wenzeslaus** [swwendel/GRASS-r.Watershed-UnitTest#1]
The following lines are unnecessary:

```
#find the list of maps
maps = get_list_of_maps()
#see if the accumulation output is in the mapset
self.assertNotIn('test_accumulation', maps, msg='The output test_accumulation already exists')
#see if the basin output is in the mapset
self.assertNotIn('test_basin', maps, msg='The output test_basin already exists')
```

Its true that the maps should not exist prior running the module. However, the module itself checks the existence of the maps and will not run if maps exist already. After running the test, maps are removed by tearDown function.

Although there is a slight possibility that the module will not check (programmer's error) and at the same time maps will be already present (probably tester's error), we don't check for this because the probability is very low (*) and it is not worth the extra lines (and complexity).

(*) We should be cautions with tests but it is really practically zero.

**Comment by swwendel** [comment]
That makes sense. I'll remove it in the next iteration. 

Thanks!

**Comment by swwendel** [comment]
Removed this section of code in version 1.1
