### ISSUE TITLE
Use more informative messages in assert calls

### ISSUE THREAD

**Issue by wenzeslaus** [swwendel/GRASS-r.Watershed-UnitTest#13]
The `test_OutputCreated()` function has a lot of assert calls which have set the (optional) `msg` parameter. The text which is currently there, e.g. "test_accumulation output was not created" is not necessary because this is what the assert function will say as well. All assert functions in `unittest` have some default message which can be replaced or enhanced by more specific message (`gunittest` follows the same practice).

I suggest to use messages which will add information, specifically use module option name instead of an map name.

http://grass.osgeo.org/grass71/manuals/libpython/gunittest.html#gunittest.case.TestCase.assertRasterExists
http://grass.osgeo.org/grass71/manuals/libpython/_modules/gunittest/case.html#TestCase.assertRasterExists

**Comment by swwendel** [comment]
Changed the message to use the parameter name being checked for instead of the direct raster name. That will be more directly linked to what parameter is the problem in the code instead of the raster name which might not be associated with the correct raster.
